import random

def generate_sentence(situation, drug, dosage, quantity, route, time_of_action, symptom, injury_cause, equipment, location, vital_sign):
    sentence_templates = [
            f"{situation} The EMS provider administered {quantity} of {drug} {dosage} via {route}  {time_of_action} to stabilize the condition.",
            f"To prevent further deterioration, {quantity} of {drug} {dosage} was given {time_of_action}   through {route}. {situation}",
            f"{situation} It was necessary to deliver {quantity} of {drug} {dosage}  {route} {time_of_action} as part of the treatment.",
            f"Following protocol, the EMS team quickly gave {quantity} of {drug} {dosage} using  {route}. {situation}",
            f"The patient’s state required {quantity} of {drug} {dosage} administered {route} {time_of_action}. {situation}",
            f"After observing critical symptoms, the EMS team decided to give {quantity} of {drug} {dosage} {route} {time_of_action}. {situation}",
            f"{situation} The doctor instructed to administer {quantity} of {drug} {dosage}  via {route} at {time_of_action} to avoid further complications.",
            f"The paramedics assessed the situation and delivered {quantity} of {drug} {dosage} through {route} {time_of_action}. {situation}",
            f"{quantity} of {drug} {dosage} was deemed necessary {time_of_action} and was given {route}. {situation}",
            f"A rapid decision was made to use {quantity} of {drug} {dosage} in order to stabilize the patient {route} {time_of_action}. {situation}",
            f"Urgent care was required, so the EMS team quickly administered {quantity} of {drug} {dosage} {route} {time_of_action}. {situation}",
            f"{situation} Without delay, the patient was given {quantity} of {drug} {dosage} using {route}  {time_of_action} to ensure stability.",
            f"In an effort to relieve symptoms, the medical team provided {quantity} of {drug} {dosage} {route}   {time_of_action}. {situation}",
            f"Medical personnel decided to administer {quantity} of {drug} {dosage} through {route} to manage the emergency {time_of_action}. {situation}",
            f"{situation} EMS responders carefully measured {quantity} of {drug} {dosage} before giving it {route} {time_of_action} to avoid complications.",
            f"An immediate dose of {quantity} of {drug} {dosage} was necessary {time_of_action} and was quickly given {route}. {situation}",
            f"The situation was critical, so {quantity} of {drug} {dosage} was administered {route} {time_of_action} with precision. {situation}",
            f"{situation} The paramedics wasted no time_of_action in delivering {quantity} of {drug} {dosage} {route}   {time_of_action} to stabilize the patient.",
            f"To counteract symptoms, {quantity} of {drug} {dosage} was applied {route} at {time_of_action}. {situation}",
            f"Due to the patient's {symptom}, {quantity} of {drug} {dosage} was administered {time_of_action} via {route}. {situation}",
            f"After assessing the patient's {symptom}, {quantity} of {drug} {dosage} was given {route} {time_of_action}. {situation}",
            f"The EMS provider noted {vital_sign} irregularities and immediately administered {quantity} of {drug} {dosage} {route}. {situation}",
            f"While at the {location}, the EMS team delivered {quantity} of {drug} {dosage} {route} {time_of_action}. {situation}",
            f"Following the injury due to {injury_cause}, {quantity} of {drug} {dosage} was given via {route} {time_of_action}. {situation}",
            f"In response to {injury_cause}, the EMS team used {equipment} and delivered {quantity} of {drug} {dosage} via {route} {time_of_action}.",
            f"The patient was found at the {location}. The EMS provider administered {quantity} of {drug} {dosage} via {route} {time_of_action}.",
            f"After the {location} incident, {quantity} of {drug} {dosage} was administered {time_of_action} to prevent worsening symptoms.",
            f"Upon arrival at the {location}, the paramedic checked vital signs, including {vital_sign}, and administered {quantity} of {drug} {dosage} {route} {time_of_action}.",
            f"{situation} After checking {vital_sign}, {quantity} of {drug} {dosage} was given through {route} {time_of_action}.",
            f"To address {symptom}, {quantity} of {drug} {dosage} was administered {route} {time_of_action}. {situation}",
            f"The EMS team quickly stabilized the patient by administering {quantity} of {drug} {dosage} via {route} {time_of_action}. {situation}",
            f"Due to the {injury_cause}, {quantity} of {drug} {dosage} was delivered via {route} at {time_of_action}. {situation}",
            f"After a quick assessment, the EMS team administered {quantity} of {drug} {dosage} via {route} {time_of_action} to address {symptom}.",
            f"{situation} {quantity} of {drug} {dosage} was given {time_of_action} to treat {symptom}. {route} was used for delivery.",
            f"Following the emergency at {location}, {quantity} of {drug} {dosage} was administered through {route} {time_of_action}.",
            f"The paramedic used {equipment} to prepare the patient, administering {quantity} of {drug} {dosage} via {route}. {situation}",
            f"After {time_of_action}, the patient was administered {quantity} of {drug} {dosage} via {route} to alleviate {symptom}. {situation}",
            f"To address the symptoms of {symptom}, {quantity} of {drug} {dosage} was given via {route} {time_of_action}. {situation}",
            f"In response to the patient's {symptom}, {quantity} of {drug} {dosage} was delivered via {route} {time_of_action}.",
            f"Following the {injury_cause}, {quantity} of {drug} {dosage} was given via {route} to prevent further injury. {time_of_action} was observed.",
            f"At {location}, after assessing the patient, {quantity} of {drug} {dosage} was given {time_of_action} via {route}.",
            f"The EMS team quickly administered {quantity} of {drug} {dosage} via {route} to stabilize the patient before {time_of_action}.",
            f"After noting {symptom}, {quantity} of {drug} {dosage} was given {route} {time_of_action}. {situation}",
            f"To address the injury caused by {injury_cause}, the EMS team administered {quantity} of {drug} {dosage} via {route} {time_of_action}.",
            f"Upon arriving at the scene, the EMS provider administered {quantity} of {drug} {dosage} {route} at {time_of_action} to manage {symptom}.",
            f"The patient was transported using {equipment} and {quantity} of {drug} {dosage} was administered {time_of_action} via {route}. {situation}",
            f"Following the patient's emergency, {quantity} of {drug} {dosage} was delivered via {route} {time_of_action} to treat {symptom}.",
            f"At the {location}, after initial assessment, {quantity} of {drug} {dosage} was given via {route} to stabilize the patient {time_of_action}.",
            f"{quantity} of {drug} {dosage} was given via {route} {time_of_action} due to the patient's condition. {situation}",
            f"During the incident at {location}, the EMS provider delivered {quantity} of {drug} {dosage} via {route} {time_of_action}.",
            f"Following the protocol for {symptom}, {quantity} of {drug} {dosage} was administered {route} at {time_of_action}. {situation}",
            f"In response to the patient's symptoms, {quantity} of {drug} {dosage} was delivered {route} at {time_of_action}. {situation}",
            f"{situation} {quantity} of {drug} {dosage} was administered {time_of_action} via {route} to address the injury.",
            f"{situation} After using {equipment}, the EMS team delivered {quantity} of {drug} {dosage} via {route}. {time_of_action} was observed.",
            f"Upon arrival, the EMS team administered {quantity} of {drug} {dosage} {route} {time_of_action} to address {symptom}.",
            f"{quantity} of {drug} {dosage} was given at {location} {time_of_action} to manage the patient's condition. {route} was used for delivery.",
            f"We administered {quantity} of {drug} {dosage} via {route} to John Doe {time_of_action} as part of the treatment for {symptom}. The {equipment} was used to stabilize the patient in {location}.",
            f"To prevent further deterioration, {quantity} of {drug} {dosage} was given to Jane Smith {time_of_action} through {route}. The situation with {symptom} required {equipment} in {location}.",
            f"After {situation}, we administered {quantity} of {drug} {dosage} {route} {time_of_action} to Alice Johnson. {vital_sign} monitoring was essential during this time.",
            f"During {situation}, Bob Brown was administered {quantity} of {drug} {dosage} via {route} {time_of_action} to manage {symptom}. We used {equipment} in {location}.",
            f"Following {situation}, we delivered {quantity} of {drug} {dosage} {route} {time_of_action} to Charlie Davis as {symptom} was observed. The equipment used in {location} helped stabilize the condition.",
            f"We administered {quantity} of {drug} {dosage} to Emma Wilson {time_of_action} via {route} to address {symptom}. The {equipment} was essential at {location}.",
            f"Michael Clark was given {quantity} of {drug} {dosage} {route} {time_of_action}. The {equipment} was used to manage {symptom} at {location}.",
            f"As part of the treatment for {symptom}, we gave {quantity} of {drug} {dosage} to Liam Lewis {time_of_action} via {route}. {vital_sign} monitoring was done at {location}.",
            f"To stabilize Olivia Harris, we administered {quantity} of {drug} {dosage} {route} {time_of_action} after {situation}. {equipment} was used at {location}.",
            f"Following {situation}, we administered {quantity} of {drug} {dosage} to Sophia Martinez {time_of_action}. The {equipment} was utilized at {location} for {symptom}.",
            f"After {situation}, we gave {quantity} of {drug} {dosage} to Noah Robinson {route} {time_of_action}. Monitoring vital signs in {location} was essential.",
            f"We quickly administered {quantity} of {drug} {dosage} {route} to William Lewis {time_of_action} to treat {symptom}. {equipment} was used at {location}.",
            f"Chloe Walker received {quantity} of {drug} {dosage} {route} {time_of_action} as {symptom} was detected. The {equipment} was vital in {location}.",
            f"In response to {situation}, James Young was administered {quantity} of {drug} {dosage} via {route} {time_of_action}. The {equipment} in {location} helped treat {symptom}.",
            f"After assessing Lily King’s condition, we administered {quantity} of {drug} {dosage} {route} {time_of_action}. {equipment} was used at {location} for {symptom}.",
            f"As {symptom} worsened, we gave {quantity} of {drug} {dosage} to Lucas Scott {route} {time_of_action}. The {equipment} at {location} was essential.",
            f"To stabilize Ava Green, we administered {quantity} of {drug} {dosage} {route} {time_of_action}. The {equipment} in {location} was crucial for {symptom}.",
            f"We administered {quantity} of {drug} {dosage} {route} to Mason Harris {time_of_action} as part of the treatment for {symptom}. The {equipment} was used in {location}.",
            f"After {situation}, we administered {quantity} of {drug} {dosage} to Ethan Baker {route} {time_of_action}. The equipment used in {location} helped stabilize {symptom}.",
            f"During {situation}, we gave {quantity} of {drug} {dosage} {route} to Grace Lee {time_of_action} to address {symptom}. {equipment} was utilized at {location}.",
            f"We gave {quantity} of {drug} {dosage} {route} to Isabella Carter {time_of_action}. The {equipment} in {location} was crucial for {symptom}.",
            f"As {symptom} worsened, we administered {quantity} of {drug} {dosage} to Lucas Allen {route} {time_of_action}. The {equipment} was essential in {location}.",
            f"We administered {quantity} of {drug} {dosage} to Charlotte Evans {route} {time_of_action} as part of the treatment for {symptom}. The {equipment} was utilized at {location}.",
            f"In response to {situation}, we gave {quantity} of {drug} {dosage} {route} {time_of_action} to Mia Gonzalez. The {equipment} was used in {location} for {symptom}.",
            f"After {situation}, we administered {quantity} of {drug} {dosage} {route} {time_of_action} to Jacob Nelson. {vital_sign} monitoring was crucial in {location}.",
            f"We quickly administered {quantity} of {drug} {dosage} to Ella Carter {route} {time_of_action} to stabilize the situation. {equipment} was used in {location}.",
            f"During {situation}, we gave {quantity} of {drug} {dosage} {route} {time_of_action} to Aiden Perez. The {equipment} helped manage {symptom} in {location}.",
            f"After {situation}, we gave {quantity} of {drug} {dosage} to Harper Miller {route} {time_of_action}. Vital sign monitoring was performed in {location}.",
            f"In response to {symptom}, we administered {quantity} of {drug} {dosage} to Mason Wilson {route} {time_of_action}. {equipment} was used to manage the situation in {location}.",
            f"We gave {quantity} of {drug} {dosage} to Benjamin Moore {route} {time_of_action} after {situation}. The {equipment} in {location} helped manage {symptom}.",
            f"Following protocol, we administered {quantity} of {drug} {dosage} {route} to Scarlett Perez {time_of_action}. The {equipment} in {location} helped stabilize {symptom}.",
            f"In response to {situation}, we gave {quantity} of {drug} {dosage} {route} {time_of_action} to Oliver Martin. The {equipment} in {location} helped control {symptom}.",
            f"We administered {quantity} of {drug} {dosage} {route} to Elijah Adams {time_of_action} for {symptom}. The {equipment} was vital in {location}.",
            f"Following {situation}, we gave {quantity} of {drug} {dosage} to Zoe Jackson {route} {time_of_action}. The {equipment} was used in {location} for {symptom}.",
            f"We gave {quantity} of {drug} {dosage} {route} to Wyatt King {time_of_action} for {symptom}. The {equipment} was used to stabilize the condition in {location}.",
            f"During {situation}, we gave {quantity} of {drug} {dosage} {route} to Natalie Mitchell {time_of_action}. The {equipment} in {location} was critical in stabilizing {symptom}.",
            f"We administered {quantity} of {drug} {dosage} {route} to Abigail Lee {time_of_action}. {equipment} was crucial in {location} for managing {symptom}.",
            f"As {symptom} worsened, we administered {quantity} of {drug} {dosage} to Grayson Perez {route} {time_of_action}. {equipment} was used in {location}.",
            f"We administered {quantity} of {drug} {dosage} to Matthew Thomas {route} {time_of_action} to treat {symptom}. The {equipment} was essential in {location}.",
            f"Following {situation}, we gave {quantity} of {drug} {dosage} to Riley Carter {route} {time_of_action}. The {equipment} in {location} was vital for {symptom}.",
            f"As {symptom} worsened, we administered {quantity} of {drug} {dosage} to Elijah Harris {route} {time_of_action}. {equipment} was critical in {location} for stabilizing the situation.",
            f"We quickly gave {quantity} of {drug} {dosage} to Isabella Wilson {route} {time_of_action} as {symptom} worsened.",
            f"During {situation}, we used {equipment} to address {symptom} in {location}. Vital signs were monitored to ensure the patient's stability.",
            f"In response to {situation}, we observed {symptom} and used {equipment} in {location}. {vital_sign} readings were checked for any abnormalities.",
            f"Following {situation}, the patient exhibited {symptom}. We utilized {equipment} at {location} to stabilize the situation and monitored {vital_sign}.",
            f"After {situation}, {symptom} was detected. The {equipment} was employed in {location}, and we closely monitored {vital_sign} to ensure patient safety.",
            f"Due to {situation}, we saw signs of {symptom}. The {equipment} was used in {location} for further assessment while {vital_sign} was checked.",
            f"As {situation} unfolded, the patient experienced {symptom}. We used {equipment} in {location} to monitor and stabilize {vital_sign}.",
            f"After {situation}, {symptom} worsened. We applied {equipment} at {location} and continuously observed {vital_sign} to gauge recovery.",
            f"Following {situation}, {symptom} was reported, so we utilized {equipment} at {location} to manage the situation and monitor {vital_sign}.",
            f"In response to {situation}, the patient was affected by {symptom}. We used {equipment} in {location} to assess {vital_sign} levels.",
            f"During {situation}, {symptom} appeared, so {equipment} was employed at {location} while {vital_sign} readings were carefully monitored.",
            f"After {situation}, the patient showed signs of {symptom}. The {equipment} was used at {location} to ensure {vital_sign} remained stable.",
            f"As part of the treatment for {symptom}, we employed {equipment} at {location}. {vital_sign} was continuously checked during {situation}.",
            f"Following {situation}, the patient displayed {symptom}. We applied {equipment} at {location}, and {vital_sign} was regularly monitored.",
            f"During {situation}, {symptom} was observed, requiring {equipment} at {location}. Vital signs were monitored throughout the process.",
            f"After {situation}, {symptom} was evident. We used {equipment} in {location} and checked {vital_sign} for any irregularities.",
            f"In response to {situation}, the patient reported {symptom}. We utilized {equipment} at {location} to monitor {vital_sign} and stabilize the condition.",
            f"Following {situation}, the patient exhibited {symptom}. We used {equipment} in {location} while keeping track of {vital_sign}.",
            f"As {situation} unfolded, the patient began showing signs of {symptom}. We applied {equipment} in {location}, closely monitoring {vital_sign}.",
            f"In response to {situation}, {symptom} developed. We used {equipment} at {location} to manage the situation, ensuring {vital_sign} remained stable.",
            f"After {situation}, {symptom} worsened. The {equipment} was deployed in {location} while {vital_sign} levels were closely monitored.",
            f"Following {situation}, {symptom} became more severe. We used {equipment} in {location} to assess and stabilize {vital_sign}.",
            f"Due to {situation}, the patient experienced {symptom}. We utilized {equipment} in {location} to manage {vital_sign} and monitor recovery.",
            f"In response to {situation}, {symptom} appeared. We used {equipment} in {location} to monitor {vital_sign} levels and ensure proper care.",
            f"During {situation}, {symptom} was observed, requiring immediate use of {equipment} at {location}. {vital_sign} was constantly monitored.",
            f"After {situation}, {symptom} emerged. We deployed {equipment} at {location} while observing {vital_sign} to assess the patient's condition.",
            f"As {situation} progressed, {symptom} was noted. We used {equipment} in {location} to manage and observe {vital_sign}.",
            f"Following {situation}, {symptom} was evident. We employed {equipment} at {location} to monitor {vital_sign} and assist in treatment.",
            f"In response to {situation}, the patient began showing signs of {symptom}. We used {equipment} at {location} and tracked {vital_sign}.",
            f"After {situation}, {symptom} became evident. We applied {equipment} in {location}, carefully monitoring {vital_sign} throughout the process.",
            f"Following {situation}, {symptom} intensified. We used {equipment} in {location} to stabilize {vital_sign} levels.",
            f"As {situation} unfolded, the patient exhibited {symptom}. {equipment} was used in {location} to monitor and stabilize {vital_sign}.",
            f"During {situation}, {symptom} became noticeable. We used {equipment} at {location} and closely observed {vital_sign}.",
            f"In response to {situation}, {symptom} was reported. We used {equipment} at {location} and monitored {vital_sign} to ensure patient safety.",
            f"After {situation}, {symptom} was detected. The {equipment} in {location} helped stabilize the patient while {vital_sign} was checked regularly.",
            f"Following {situation}, the patient experienced {symptom}. We utilized {equipment} in {location} to stabilize {vital_sign}.",
            f"As {situation} progressed, {symptom} was observed. We used {equipment} at {location} and monitored {vital_sign} for any changes.",
            f"During {situation}, {symptom} was present, requiring the use of {equipment} at {location}. {vital_sign} was checked frequently.",
            f"In response to {situation}, {symptom} emerged. We applied {equipment} at {location} to monitor {vital_sign} and stabilize the condition.",
            f"After {situation}, {symptom} worsened. We used {equipment} at {location} to check and stabilize {vital_sign}.",
            f"Following {situation}, {symptom} was evident. We used {equipment} in {location} to stabilize the situation and monitored {vital_sign}.",
            f"As part of the response to {situation}, we used {equipment} to manage {symptom}. {vital_sign} was continuously checked during the procedure in {location}.",
            f"In response to {situation}, {symptom} appeared. {equipment} was used in {location} to stabilize {vital_sign} and ensure the patient's condition improved.",
            f"After {situation}, the patient exhibited {symptom}. We used {equipment} at {location} to stabilize {vital_sign} and improve the condition.",
            f"Following {situation}, we used {equipment} in {location} to manage {symptom}. {vital_sign} levels were monitored during the process.",
            f"As {situation} progressed, {symptom} appeared. We used {equipment} in {location} and observed {vital_sign} to stabilize the patient.",
            f"In response to {situation}, we administered {equipment} at {location}. {symptom} was managed, and {vital_sign} levels were checked.",
            f"Following {situation}, {symptom} appeared. We used {equipment} at {location} and kept track of {vital_sign} to monitor the patient's condition.",
            f"During {situation}, {symptom} was noted. {equipment} was used in {location}, and {vital_sign} was observed to ensure recovery.",
            f"During {situation}, we used {equipment} to address {symptom} in {location}. Vital signs were monitored to ensure the patient's stability.",
            f"In response to {situation}, we observed {symptom} and used {equipment} in {location}. {vital_sign} readings were checked for any abnormalities.",
            f"Following {situation}, the patient exhibited {symptom}. We utilized {equipment} at {location} to stabilize the situation and monitored {vital_sign}.",
            f"After {situation}, {symptom} was detected. The {equipment} was employed in {location}, and we closely monitored {vital_sign} to ensure patient safety.",
            f"Due to {situation}, we saw signs of {symptom}. The {equipment} was used in {location} for further assessment while {vital_sign} was checked.",
            f"As {situation} unfolded, the patient experienced {symptom}. We used {equipment} in {location} to monitor and stabilize {vital_sign}.",
            f"After {situation}, {symptom} worsened. We applied {equipment} at {location} and continuously observed {vital_sign} to gauge recovery.",
            f"Following {situation}, {symptom} was reported, so we utilized {equipment} at {location} to manage the situation and monitor {vital_sign}.",
            f"In response to {situation}, the patient was affected by {symptom}. We used {equipment} in {location} to assess {vital_sign} levels.",
            f"During {situation}, {symptom} appeared, so {equipment} was employed at {location} while {vital_sign} readings were carefully monitored.",
            f"After {situation}, the patient showed signs of {symptom}. The {equipment} was used at {location} to ensure {vital_sign} remained stable.",
            f"As part of the treatment for {symptom}, we employed {equipment} at {location}. {vital_sign} was continuously checked during {situation}.",
            f"Following {situation}, the patient displayed {symptom}. We applied {equipment} at {location}, and {vital_sign} was regularly monitored.",
            f"During {situation}, {symptom} was observed, requiring {equipment} at {location}. Vital signs were monitored throughout the process.",
            f"After {situation}, {symptom} was evident. We used {equipment} in {location} and checked {vital_sign} for any irregularities.",
            f"In response to {situation}, the patient reported {symptom}. We utilized {equipment} at {location} to monitor {vital_sign} and stabilize the condition.",
            f"Following {situation}, the patient exhibited {symptom}. We used {equipment} in {location} while keeping track of {vital_sign}.",
            f"As {situation} unfolded, the patient began showing signs of {symptom}. We applied {equipment} in {location}, closely monitoring {vital_sign}.",
            f"In response to {situation}, {symptom} developed. We used {equipment} at {location} to manage the situation, ensuring {vital_sign} remained stable.",
            f"After {situation}, {symptom} worsened. The {equipment} was deployed in {location} while {vital_sign} levels were closely monitored.",
            f"Following {situation}, {symptom} became more severe. We used {equipment} in {location} to assess and stabilize {vital_sign}.",
            f"Due to {situation}, the patient experienced {symptom}. We utilized {equipment} in {location} to manage {vital_sign} and monitor recovery.",
            f"In response to {situation}, {symptom} appeared. We used {equipment} in {location} to monitor {vital_sign} levels and ensure proper care.",
            f"During {situation}, {symptom} was observed, requiring immediate use of {equipment} at {location}. {vital_sign} was constantly monitored.",
            f"After {situation}, {symptom} emerged. We deployed {equipment} at {location} while observing {vital_sign} to assess the patient's condition.",
            f"As {situation} progressed, {symptom} was noted. We used {equipment} in {location} to manage and observe {vital_sign}.",
            f"Following {situation}, {symptom} was evident. We employed {equipment} at {location} to monitor {vital_sign} and assist in treatment.",
            f"In response to {situation}, the patient began showing signs of {symptom}. We used {equipment} at {location} and tracked {vital_sign}.",
            f"After {situation}, {symptom} became evident. We applied {equipment} in {location}, carefully monitoring {vital_sign} throughout the process.",
            f"Following {situation}, {symptom} intensified. We used {equipment} in {location} to stabilize {vital_sign} levels.",
            f"As {situation} unfolded, the patient exhibited {symptom}. {equipment} was used in {location} to monitor and stabilize {vital_sign}.",
            f"During {situation}, {symptom} became noticeable. We used {equipment} at {location} and closely observed {vital_sign}.",
            f"In response to {situation}, {symptom} was reported. We used {equipment} at {location} and monitored {vital_sign} to ensure patient safety.",
            f"After {situation}, {symptom} was detected. The {equipment} in {location} helped stabilize the patient while {vital_sign} was checked regularly.",
            f"Following {situation}, the patient experienced {symptom}. We utilized {equipment} in {location} to stabilize {vital_sign}.",
            f"As {situation} progressed, {symptom} was observed. We used {equipment} at {location} and monitored {vital_sign} for any changes.",
            f"During {situation}, {symptom} was present, requiring the use of {equipment} at {location}. {vital_sign} was checked frequently.",
            f"In response to {situation}, {symptom} emerged. We applied {equipment} at {location} to monitor {vital_sign} and stabilize the condition.",
            f"After {situation}, {symptom} worsened. We used {equipment} at {location} to check and stabilize {vital_sign}.",
            f"Following {situation}, {symptom} was evident. We used {equipment} in {location} to stabilize the situation and monitored {vital_sign}.",
            f"As part of the response to {situation}, we used {equipment} to manage {symptom}. {vital_sign} was continuously checked during the procedure in {location}.",
            f"In response to {situation}, {symptom} appeared. {equipment} was used in {location} to stabilize {vital_sign} and ensure the patient's condition improved.",
            f"After {situation}, the patient exhibited {symptom}. We used {equipment} at {location} to stabilize {vital_sign} and improve the condition.",
            f"Following {situation}, we used {equipment} in {location} to manage {symptom}. {vital_sign} levels were monitored during the process.",
            f"As {situation} progressed, {symptom} appeared. We used {equipment} in {location} and observed {vital_sign} to stabilize the patient.",
            f"In response to {situation}, we administered {equipment} at {location}. {symptom} was managed, and {vital_sign} levels were checked.",
            f"Following {situation}, {symptom} appeared. We used {equipment} at {location} and kept track of {vital_sign} to monitor the patient's condition.",
            f"During {situation}, {symptom} was noted. {equipment} was used in {location}, and {vital_sign} was observed to ensure recovery.",
            f"During {situation}, we observed {symptom} and detected {injury_cause} in {location}. We used {equipment} to address the situation while monitoring {vital_sign}.",
            f"In response to {situation}, the patient exhibited {symptom} and a potential {injury_cause} at {location}. We used {equipment} to manage the situation and tracked {vital_sign}.",
            f"Following {situation}, {symptom} and {injury_cause} were observed. We applied {equipment} in {location} while monitoring {vital_sign} to assess the patient's condition.",
            f"After {situation}, the patient showed signs of {symptom} and {injury_cause}. We employed {equipment} in {location} and closely observed {vital_sign}.",
            f"Due to {situation}, {symptom} and {injury_cause} were detected. We used {equipment} at {location} and monitored {vital_sign} to ensure the patient's stability.",
            f"As {situation} unfolded, {symptom} and {injury_cause} were noted. We applied {equipment} in {location}, and {vital_sign} was carefully monitored.",
            f"Following {situation}, the patient experienced {symptom} and {injury_cause}. We utilized {equipment} in {location} and tracked {vital_sign} to stabilize the condition.",
            f"After {situation}, the patient showed signs of {symptom} and {injury_cause}. We used {equipment} in {location} while checking {vital_sign} frequently.",
            f"Due to {situation}, {symptom} and {injury_cause} were observed. We applied {equipment} at {location} and continuously monitored {vital_sign}.",
            f"As {situation} progressed, the patient exhibited {symptom} and {injury_cause}. We used {equipment} in {location} and monitored {vital_sign} for any changes.",
            f"During {situation}, the patient reported {symptom} and {injury_cause} at {location}. We employed {equipment} and kept a close watch on {vital_sign}.",
            f"Following {situation}, {symptom} and {injury_cause} were observed. We utilized {equipment} at {location} to stabilize {vital_sign}.",
            f"As part of the response to {situation}, {symptom} and {injury_cause} became evident. We applied {equipment} at {location} to manage {vital_sign}.",
            f"After {situation}, the patient was affected by {symptom} and {injury_cause}. We used {equipment} in {location} to stabilize the situation while monitoring {vital_sign}.",
            f"In response to {situation}, {symptom} and {injury_cause} were detected. We applied {equipment} at {location} and monitored {vital_sign} to gauge recovery.",
            f"Following {situation}, {symptom} and {injury_cause} were evident. {equipment} was used at {location} to assist with stabilization while monitoring {vital_sign}.",
            f"After {situation}, the patient displayed {symptom} and {injury_cause}. We employed {equipment} in {location} and tracked {vital_sign} closely.",
            f"As {situation} unfolded, {symptom} and {injury_cause} were reported. We applied {equipment} in {location}, observing {vital_sign} throughout the process.",
            f"In response to {situation}, {symptom} and {injury_cause} were present. We used {equipment} at {location} to assess and monitor {vital_sign}.",
            f"After {situation}, {symptom} and {injury_cause} worsened. We used {equipment} in {location} while checking {vital_sign}.",
            f"Following {situation}, {symptom} and {injury_cause} were observed. We applied {equipment} at {location} and monitored {vital_sign} throughout the treatment.",
            f"As {situation} progressed, {symptom} and {injury_cause} were observed. We applied {equipment} in {location}, constantly monitoring {vital_sign}.",
            f"In response to {situation}, the patient exhibited {symptom} and {injury_cause}. We used {equipment} at {location} to assess and monitor {vital_sign}.",
            f"After {situation}, {symptom} and {injury_cause} were noted. We used {equipment} in {location} to ensure {vital_sign} remained stable.",
            f"Following {situation}, {symptom} and {injury_cause} were detected. We applied {equipment} at {location} and monitored {vital_sign} throughout the treatment.",
            f"As part of the treatment for {symptom} and {injury_cause}, we applied {equipment} in {location}. {vital_sign} was continuously checked during {situation}.",
            f"In response to {situation}, the patient showed signs of {symptom} and {injury_cause}. We used {equipment} at {location} to monitor {vital_sign}.",
            f"During {situation}, the patient experienced {symptom} and {injury_cause}. We applied {equipment} in {location}, closely observing {vital_sign}.",
            f"After {situation}, {symptom} and {injury_cause} were noted. We used {equipment} in {location} while monitoring {vital_sign} for changes.",
            f"Following {situation}, {symptom} and {injury_cause} worsened. We employed {equipment} at {location}, keeping track of {vital_sign}.",
            f"During {situation}, {symptom} and {injury_cause} were present. We used {equipment} in {location} to stabilize {vital_sign}.",
            f"Following {situation}, the patient showed {symptom} and {injury_cause}. We used {equipment} at {location} to monitor {vital_sign} and stabilize the patient.",
            f"As {situation} progressed, {symptom} and {injury_cause} were observed. We applied {equipment} in {location}, constantly monitoring {vital_sign}.",
            f"In response to {situation}, the patient exhibited {symptom} and {injury_cause}. We used {equipment} at {location} to assess and monitor {vital_sign}.",
            f"After {situation}, {symptom} and {injury_cause} were noted. We used {equipment} in {location} to ensure {vital_sign} remained stable.",
            f"Following {situation}, {symptom} and {injury_cause} were detected. We applied {equipment} at {location} and monitored {vital_sign} throughout the treatment.",
            f"After {situation}, the patient showed signs of {symptom} and {injury_cause}. We used {equipment} in {location} and tracked {vital_sign}.",
            f"During {situation}, {symptom} and {injury_cause} were observed. We applied {equipment} at {location} while continuously tracking {vital_sign}.",
            f"In response to {situation}, {symptom} and {injury_cause} were present. We utilized {equipment} at {location} to monitor {vital_sign}.",
            f"After {situation}, {symptom} and {injury_cause} worsened. We used {equipment} in {location} while checking {vital_sign}.",
            f"Following {situation}, {symptom} and {injury_cause} were evident. We applied {equipment} at {location} to stabilize {vital_sign}.",
            f"As {situation} unfolded, {symptom} and {injury_cause} developed. We used {equipment} in {location} to monitor {vital_sign} levels.",
            f"During {situation}, {symptom} and {injury_cause} were detected. We employed {equipment} at {location} to stabilize {vital_sign}.",
            f"After {situation}, {symptom} and {injury_cause} worsened. We applied {equipment} in {location} while checking {vital_sign} frequently.",
            f"Following {situation}, {symptom} and {injury_cause} were reported. We used {equipment} at {location} and monitored {vital_sign} levels.",
            f"In response to {situation}, {symptom} and {injury_cause} emerged. We used {equipment} at {location} to stabilize {vital_sign}.",
            f"After {situation}, the patient exhibited {symptom} and {injury_cause}. We used {equipment} at {location} and tracked {vital_sign}.",
            f"During {situation}, {symptom} and {injury_cause} appeared. We used {equipment} in {location}, constantly monitoring {vital_sign}.",
            f"In response to {situation}, {symptom} and {injury_cause} were present. We used {equipment} in {location} to monitor {vital_sign}.",
            f"Following {situation}, {symptom} and {injury_cause} became evident. We employed {equipment} in {location} and closely monitored {vital_sign}.",
            f"After {situation}, the patient showed signs of {symptom} and {injury_cause}. We used {equipment} in {location} and checked {vital_sign}.",
            f"During {situation}, {symptom} and {injury_cause} were detected. We used {equipment} in {location} to monitor {vital_sign}.",
        ]
    
    sentence = random.choice(sentence_templates)
    
    return sentence
